package isfdyt5.poo.proyectofinal;

/**
 *
 * @author Mario
 */
public class VentanaVentas extends javax.swing.JFrame {

    public final Empresa empresa;
    /**
     * Creates new form VentanaVentas
     */
    public VentanaVentas() {
        initComponents();
        setLocationRelativeTo(null);
        Empresa e1 = new Empresa("Mi Empresa");
        empresa = e1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCheckBoxDescuento = new javax.swing.JCheckBox();
        jCheckBoxDelivery = new javax.swing.JCheckBox();
        jRadioButtonEnvaseChico = new javax.swing.JRadioButton();
        jRadioButtonEnvaseMedio = new javax.swing.JRadioButton();
        jRadioButtonEnvaseGrande = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jCheckBoxGusto1 = new javax.swing.JCheckBox();
        jCheckBoxGusto2 = new javax.swing.JCheckBox();
        jCheckBoxGusto3 = new javax.swing.JCheckBox();
        jCheckBoxGusto4 = new javax.swing.JCheckBox();
        jSpinnerEnvaseChico = new javax.swing.JSpinner();
        jSpinnerEnvaseMedio = new javax.swing.JSpinner();
        jSpinnerEnvaseGrande = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Ventas");

        jButton1.setText("Volver al Menu Principal");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre Cliente");

        jLabel2.setText("Direccion");

        jCheckBoxDescuento.setText("Descuento");

        jCheckBoxDelivery.setText("Delivery");

        buttonGroup1.add(jRadioButtonEnvaseChico);
        jRadioButtonEnvaseChico.setText("Envase Chico");

        buttonGroup1.add(jRadioButtonEnvaseMedio);
        jRadioButtonEnvaseMedio.setText("Envase Medio");

        buttonGroup1.add(jRadioButtonEnvaseGrande);
        jRadioButtonEnvaseGrande.setText("Envase Grande");

        jButton2.setText("Agregar Venta");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jCheckBoxGusto1.setText("Gusto 1");

        jCheckBoxGusto2.setText("Gusto 2");

        jCheckBoxGusto3.setText("Gusto 3");

        jCheckBoxGusto4.setText("Gusto 4");

        jSpinnerEnvaseChico.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jSpinnerEnvaseMedio.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jSpinnerEnvaseGrande.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel3.setText("Cantidad");

        jLabel4.setText("Cantidad");

        jLabel5.setText("Cantidad");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(120, 120, 120))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addGap(14, 14, 14)
                        .addComponent(jSpinnerEnvaseGrande, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(jRadioButtonEnvaseChico)
                    .addComponent(jRadioButtonEnvaseMedio)
                    .addComponent(jRadioButtonEnvaseGrande)
                    .addComponent(jTextField2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSpinnerEnvaseChico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(139, 139, 139))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSpinnerEnvaseMedio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(139, 139, 139)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxDescuento)
                            .addComponent(jCheckBoxDelivery)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jCheckBoxGusto1)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBoxGusto2)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBoxGusto3)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBoxGusto4)
                        .addGap(37, 37, 37))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCheckBoxDescuento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBoxDelivery)
                            .addComponent(jRadioButtonEnvaseMedio)
                            .addComponent(jSpinnerEnvaseMedio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButtonEnvaseChico)
                        .addComponent(jSpinnerEnvaseChico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonEnvaseGrande)
                    .addComponent(jSpinnerEnvaseGrande, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxGusto1)
                    .addComponent(jCheckBoxGusto2)
                    .addComponent(jCheckBoxGusto3)
                    .addComponent(jCheckBoxGusto4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(31, 31, 31)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        this.setVisible(false);
    }                                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        obtenerVenta();
        jTextField1.setText("");
        jTextField2.setText("");
        jSpinnerEnvaseChico.setValue(0);
        jSpinnerEnvaseMedio.setValue(0);
        jSpinnerEnvaseGrande.setValue(0);
        jCheckBoxDelivery.setSelected(false);
        jCheckBoxDescuento.setSelected(false);
        jCheckBoxGusto1.setSelected(false);
        jCheckBoxGusto2.setSelected(false);
        jCheckBoxGusto3.setSelected(false);
        jCheckBoxGusto4.setSelected(false);
        jRadioButtonEnvaseChico.setSelected(false);
        jRadioButtonEnvaseMedio.setSelected(false);
        jRadioButtonEnvaseGrande.setSelected(false);
    }                                        

    public void obtenerVenta(){
    
       Cliente c1 = new Cliente(jTextField1.getText(), jTextField2.getText());
       if (jCheckBoxDescuento.isSelected()){
        Descuento de1 = new Descuento();
        c1.addCupon(de1);
       }
       if (jCheckBoxDelivery.isSelected()){
        Delivery d1 = new Delivery();
        c1.addCupon(d1);
       }
       
      
       Helado h1 = new Helado();
       h1.setCliente(c1);
       
       if(jCheckBoxGusto1.isSelected()){
        Gusto g1 = new Gusto("Gusto1");
        h1.addGusto(g1);
       }
       if(jCheckBoxGusto2.isSelected()){
        Gusto g2 = new Gusto("Gusto2");
        h1.addGusto(g2);
       }
       if(jCheckBoxGusto3.isSelected()){
        Gusto g3 = new Gusto("Gusto3");
        h1.addGusto(g3);
       }
       if(jCheckBoxGusto4.isSelected()){
        Gusto g4 = new Gusto("Gusto4");
        h1.addGusto(g4);
       }
       
       if(jRadioButtonEnvaseChico.isSelected()){
       h1.setCantidad((Integer) jSpinnerEnvaseChico.getValue());
        h1.setEnvase(Envase.CHICO);
       }
       if(jRadioButtonEnvaseMedio.isSelected()){
        h1.setCantidad((Integer) jSpinnerEnvaseMedio.getValue());
        h1.setEnvase(Envase.MEDIO);
       }
       if(jRadioButtonEnvaseGrande.isSelected()){
        h1.setCantidad((Integer) jSpinnerEnvaseGrande.getValue());
        h1.setEnvase(Envase.GRANDE);
       }
       
       Venta v1 = new Venta();
       v1.addHelado(h1);
       empresa.addVenta(v1);
       
       System.out.println("El total a combrar del cliente "+jTextField1.getText()+" es $"+v1.totalHelado(h1));
       System.out.println("El total de gustos pedidos por el cliente "+jTextField1.getText()+" es "+h1.totalGustos());
       System.out.println("");
       System.out.println("El importe total vendido por la empresa "+empresa.getNombre()+" es "+empresa.totalVentas());
       System.out.println("El total de ventas realizadas por la empresa "+empresa.getNombre()+" es "+empresa.cantidadVentas());
       System.out.println("---------------------------------------------------------------");
        
      
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaVentas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBoxDelivery;
    private javax.swing.JCheckBox jCheckBoxDescuento;
    private javax.swing.JCheckBox jCheckBoxGusto1;
    private javax.swing.JCheckBox jCheckBoxGusto2;
    private javax.swing.JCheckBox jCheckBoxGusto3;
    private javax.swing.JCheckBox jCheckBoxGusto4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton jRadioButtonEnvaseChico;
    private javax.swing.JRadioButton jRadioButtonEnvaseGrande;
    private javax.swing.JRadioButton jRadioButtonEnvaseMedio;
    private javax.swing.JSpinner jSpinnerEnvaseChico;
    private javax.swing.JSpinner jSpinnerEnvaseGrande;
    private javax.swing.JSpinner jSpinnerEnvaseMedio;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration                   
}
